# Generated by Django 5.2 on 2025-04-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kad_number', models.CharField(max_length=20)),
                ('length', models.IntegerField(max_length=20)),
                ('location', models.TextField()),
                ('property_law', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LandPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('square', models.IntegerField()),
                ('property_law', models.CharField(max_length=100)),
                ('road', models.ManyToManyField(to='roads.road')),
            ],
        ),
    ]
