# Generated by Django 5.2 on 2025-04-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='length',
            field=models.IntegerField(),
        ),
    ]
