# Generated by Django 5.2 on 2025-04-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0002_alter_road_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='ident_number',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
