# Generated by Django 5.2 on 2025-04-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0003_road_ident_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='ident_number',
            field=models.CharField(default=52, max_length=20),
        ),
    ]
