# Generated by Django 5.2 on 2025-04-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0004_alter_road_ident_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='landplot',
            name='category',
            field=models.CharField(choices=[('n', 'Земли населенных пунктов'), ('p', 'Земли промышленности'), ('s', 'Земли с/х назначения')], default='p', max_length=1),
        ),
        migrations.AddField(
            model_name='landplot',
            name='kad_number',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='landplot',
            name='vri',
            field=models.CharField(choices=[('a', 'Автомобильный транспорт'), ('o', 'Земли общего пользования')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='square',
            field=models.IntegerField(default=1),
        ),
    ]
