# Generated by Django 5.2 on 2025-04-09 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0005_landplot_category_landplot_kad_number_landplot_vri_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landplot',
            name='road',
        ),
        migrations.AddField(
            model_name='landplot',
            name='road',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roads.road'),
        ),
    ]
