# Generated by Django 5.2 on 2025-04-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0007_alter_landplot_category_alter_landplot_vri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='property_law',
            field=models.CharField(blank=True, default='Оперативное управление'),
        ),
    ]
