# Generated by Django 5.2 on 2025-04-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0009_alter_road_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='road',
            options={'ordering': ['ident_number']},
        ),
        migrations.AddField(
            model_name='landplot',
            name='document_foundation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='landplot',
            name='status',
            field=models.CharField(choices=[('1', 'Учтенный'), ('0', 'Снят с ГКУ')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='road',
            name='document_foundation',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='property_law',
            field=models.CharField(default='Постоянное (бессрочное) пользование'),
        ),
    ]
